tts_order_voice = {'English-Jenny (Woman)': 'en-US-JennyNeural',
 'English-Guy (Man)': 'en-US-GuyNeural',
 'English-Ana (Woman)': 'en-US-AnaNeural',
 'English-Aria (Woman)': 'en-US-AriaNeural',
 'English-Christopher (Man)': 'en-US-ChristopherNeural',
 'English-Eric (Man)': 'en-US-EricNeural',
 'English-Michelle (Woman)': 'en-US-MichelleNeural',
 'English-Roger (Man)': 'en-US-RogerNeural',
 'Spanish (Mexican)-Dalia (Woman)': 'es-MX-DaliaNeural',
 'Spanish (Mexican)-Jorge- (Man)': 'es-MX-JorgeNeural',
 'Korean-Sun-Hi- (Woman)': 'ko-KR-SunHiNeural',
 'Korean-InJoon- (Man)': 'ko-KR-InJoonNeural',
'Thai-Premwadee- (Woman)': 'th-TH-PremwadeeNeural',
 'Thai-Niwat- (Man)': 'th-TH-NiwatNeural',
 'Vietnamese-HoaiMy- (Woman)': 'vi-VN-HoaiMyNeural',
'Vietnamese-NamMinh- (Man)': 'vi-VN-NamMinhNeural',
 'Japanese-Nanami- (Woman)': 'ja-JP-NanamiNeural',
 'Japanese-Keita- (Man)': 'ja-JP-KeitaNeural',
 'French-Denise- (Woman)': 'fr-FR-DeniseNeural',
 'French-Eloise- (Woman)': 'fr-FR-EloiseNeural',
 'French-Henri- (Man)': 'fr-FR-HenriNeural',
 'Brazilian-Francisca- (Woman)': 'pt-BR-FranciscaNeural',
 'Brazilian-Antonio- (Man)': 'pt-BR-AntonioNeural',
 'Indonesian-Ardi- (Man)': 'id-ID-ArdiNeural',
 'Indonesian-Gadis- (Woman)': 'id-ID-GadisNeural',
 'Hebrew-Avri- (Man)': 'he-IL-AvriNeural',
 'Hebrew-Hila- (Woman)': 'he-IL-HilaNeural',
'Italian-Isabella- (Woman)': 'it-IT-IsabellaNeural',
 'Italian-Diego- (Man)': 'it-IT-DiegoNeural',
 'Italian-Elsa- (Woman)': 'it-IT-ElsaNeural',
 'Dutch-Colette- (Woman)': 'nl-NL-ColetteNeural',
 'Dutch-Fenna- (Woman)': 'nl-NL-FennaNeural',
 'Dutch-Maarten- (Man)': 'nl-NL-MaartenNeural',
'Malese-Osman- (Man)': 'ms-MY-OsmanNeural',
 'Malese-Yasmin- (Woman)': 'ms-MY-YasminNeural',
 'Norwegian-Pernille- (Woman)': 'nb-NO-PernilleNeural',
 'Norwegian-Finn- (Man)': 'nb-NO-FinnNeural',
 'Swedish-Sofie- (Woman)': 'sv-SE-SofieNeural',
 'ArabicSwedish-Mattias- (Man)': 'sv-SE-MattiasNeural',
 'Arabic-Hamed- (Man)': 'ar-SA-HamedNeural',
 'Arabic-Zariyah- (Woman)': 'ar-SA-ZariyahNeural',
 'Greek-Athina- (Woman)': 'el-GR-AthinaNeural',
 'Greek-Nestoras- (Man)': 'el-GR-NestorasNeural',
'German-Katja- (Woman)': 'de-DE-KatjaNeural',
 'German-Amala- (Woman)': 'de-DE-AmalaNeural',
 'German-Conrad- (Man)': 'de-DE-ConradNeural',
 'German-Killian- (Man)': 'de-DE-KillianNeural',
 'Afrikaans-Adri- (Woman)': 'af-ZA-AdriNeural',
 'Afrikaans-Willem- (Man)': 'af-ZA-WillemNeural',
 'Ethiopian-Ameha- (Man)': 'am-ET-AmehaNeural',
 'Ethiopian-Mekdes- (Woman)': 'am-ET-MekdesNeural',
 'Arabic (UAD)-Fatima- (Woman)': 'ar-AE-FatimaNeural',
 'Arabic (UAD)-Hamdan- (Man)': 'ar-AE-HamdanNeural',
 'Arabic (Bahrain)-Ali- (Man)': 'ar-BH-AliNeural',
 'Arabic (Bahrain)-Laila- (Woman)': 'ar-BH-LailaNeural',
 'Arabic (Algeria)-Ismael- (Man)': 'ar-DZ-IsmaelNeural',
 'Arabic (Egypt)-Salma- (Woman)': 'ar-EG-SalmaNeural',
 'Arabic (Egypt)-Shakir- (Man)': 'ar-EG-ShakirNeural',
 'Arabic (Iraq)-Bassel- (Man)': 'ar-IQ-BasselNeural',
 'Arabic (Iraq)-Rana- (Woman)': 'ar-IQ-RanaNeural',
 'Arabic (Jordan)-Sana- (Woman)': 'ar-JO-SanaNeural',
 'Arabic (Jordan)-Taim- (Man)': 'ar-JO-TaimNeural',
 'Arabic (Kuwait)-Fahed- (Man)': 'ar-KW-FahedNeural',
 'Arabic (Kuwait)-Noura- (Woman)': 'ar-KW-NouraNeural',
 'Arabic (Lebanon)-Layla- (Woman)': 'ar-LB-LaylaNeural',
 'Arabic (Lebanon)-Rami- (Man)': 'ar-LB-RamiNeural',
 'Arabic (Libya)-Iman- (Woman)': 'ar-LY-ImanNeural',
 'Arabic (Libya)-Omar- (Man)': 'ar-LY-OmarNeural',
 'Arabic (Morocco)-Jamal- (Man)': 'ar-MA-JamalNeural',
 'Arabic (Morocco)-Mouna- (Woman)': 'ar-MA-MounaNeural',
 'Arabic (Oman)-Abdullah- (Man)': 'ar-OM-AbdullahNeural',
 'Arabic (Oman)-Aysha- (Woman)': 'ar-OM-AyshaNeural',
 'Arabic (Qatar)-Amal- (Woman)': 'ar-QA-AmalNeural',
 'Arabic (Qatar)-Moaz- (Man)': 'ar-QA-MoazNeural',
 'Arabic (Syrian Arab Republic)-Amany- (Woman)': 'ar-SY-AmanyNeural',
 'Arabic (Syrian Arab Republic)-Laith- (Man)': 'ar-SY-LaithNeural',
 'Arabic (Tunisia)-Hedi- (Man)': 'ar-TN-HediNeural',
 'Arabic (Tunisia)-Reem- (Woman)': 'ar-TN-ReemNeural',
 'Arabic (Yemen	)-Maryam- (Woman)': 'ar-YE-MaryamNeural',
 'Arabic (Yemen	)-Saleh- (Man)': 'ar-YE-SalehNeural',
 'Azerbaijani-Babek- (Man)': 'az-AZ-BabekNeural',
 'Azerbaijani-Banu- (Woman)': 'az-AZ-BanuNeural',
 'Bulgarian-Borislav- (Man)': 'bg-BG-BorislavNeural',
 'Bulgarian-Kalina- (Woman)': 'bg-BG-KalinaNeural',
 'Bengali (Bangladesh)-Nabanita- (Woman)': 'bn-BD-NabanitaNeural',
 'Bengali (Bangladesh)-Pradeep- (Man)': 'bn-BD-PradeepNeural',
 'Bengali (India)-Bashkar- (Man)': 'bn-IN-BashkarNeural',
 'Bengali (India)-Tanishaa- (Woman)': 'bn-IN-TanishaaNeural',
 'Bosniak (Bosnia and Herzegovina)-Goran- (Man)': 'bs-BA-GoranNeural',
 'Bosniak (Bosnia and Herzegovina)-Vesna- (Woman)': 'bs-BA-VesnaNeural',
 'Catalan (Spain)-Joana- (Woman)': 'ca-ES-JoanaNeural',
 'Catalan (Spain)-Enric- (Man)': 'ca-ES-EnricNeural',
 'Czech (Czech Republic)-Antonin- (Man)': 'cs-CZ-AntoninNeural',
 'Czech (Czech Republic)-Vlasta- (Woman)': 'cs-CZ-VlastaNeural',
 'Welsh (UK)-Aled- (Man)': 'cy-GB-AledNeural',
 'Welsh (UK)-Nia- (Woman)': 'cy-GB-NiaNeural',
 'Danish (Denmark)-Christel- (Woman)': 'da-DK-ChristelNeural',
 'Danish (Denmark)-Jeppe- (Man)': 'da-DK-JeppeNeural',
 'German (Austria)-Ingrid- (Woman)': 'de-AT-IngridNeural',
 'German (Austria)-Jonas- (Man)': 'de-AT-JonasNeural',
 'German (Switzerland)-Jan- (Man)': 'de-CH-JanNeural',
 'German (Switzerland)-Leni- (Woman)': 'de-CH-LeniNeural',
 'English (Australia)-Natasha- (Woman)': 'en-AU-NatashaNeural',
 'English (Australia)-William- (Man)': 'en-AU-WilliamNeural',
 'English (Canada)-Clara- (Woman)': 'en-CA-ClaraNeural',
 'English (Canada)-Liam- (Man)': 'en-CA-LiamNeural',
 'English (UK)-Libby- (Woman)': 'en-GB-LibbyNeural',
 'English (UK)-Maisie- (Woman)': 'en-GB-MaisieNeural',
 'English (UK)-Ryan- (Man)': 'en-GB-RyanNeural',
 'English (UK)-Sonia- (Woman)': 'en-GB-SoniaNeural',
 'English (UK)-Thomas- (Man)': 'en-GB-ThomasNeural',
 'English (Hong Kong)-Sam- (Man)': 'en-HK-SamNeural',
 'English (Hong Kong)-Yan- (Woman)': 'en-HK-YanNeural',
 'English (Ireland)-Connor- (Man)': 'en-IE-ConnorNeural',
 'English (Ireland)-Emily- (Woman)': 'en-IE-EmilyNeural',
 'English (India)-Neerja- (Woman)': 'en-IN-NeerjaNeural',
 'English (India)-Prabhat- (Man)': 'en-IN-PrabhatNeural',
 'English (Kenya)-Asilia- (Woman)': 'en-KE-AsiliaNeural',
 'English (Kenya)-Chilemba- (Man)': 'en-KE-ChilembaNeural',
 'English (Nigeria)-Abeo- (Man)': 'en-NG-AbeoNeural',
'English (Nigeria)-Ezinne- (Woman)': 'en-NG-EzinneNeural',
 'English (New Zealand)-Mitchell- (Man)': 'en-NZ-MitchellNeural',
 'English (Philippines)-James- (Man)': 'en-PH-JamesNeural',
 'English (Philippines)-Rosa- (Woman)': 'en-PH-RosaNeural',
 'English (Singapore)-Luna- (Woman)': 'en-SG-LunaNeural',
 'English (Singapore)-Wayne- (Man)': 'en-SG-WayneNeural',
 'English (Tanzania)-Elimu- (Man)': 'en-TZ-ElimuNeural',
 'English (Tanzania)-Imani- (Woman)': 'en-TZ-ImaniNeural',
 'English (South Africa)-Leah- (Woman)': 'en-ZA-LeahNeural',
 'English (South Africa)-Luke- (Man)': 'en-ZA-LukeNeural',
'Spanish (Argentina)-Elena- (Woman)': 'es-AR-ElenaNeural',
 'Spanish (Argentina)-Tomas- (Man)': 'es-AR-TomasNeural',
 'Spanish (Bolivia)-Marcelo- (Man)': 'es-BO-MarceloNeural',
 'Spanish (Bolivia)-Sofia- (Woman)': 'es-BO-SofiaNeural',
 'Spanish (Colombia)-Gonzalo- (Man)': 'es-CO-GonzaloNeural',
 'Spanish (Colombia)-Salome- (Woman)': 'es-CO-SalomeNeural',
 'Spanish (Costa Rica)-Juan- (Man)': 'es-CR-JuanNeural',
 'Spanish (Costa Rica)-Maria- (Woman)': 'es-CR-MariaNeural',
 'Spanish (Cuba)-Belkys- (Woman)': 'es-CU-BelkysNeural',
 'Spanish (Dominican Republic)-Emilio- (Man)': 'es-DO-EmilioNeural',
 'Spanish (Dominican Republic)-Ramona- (Woman)': 'es-DO-RamonaNeural',
 'Spanish (Ecuador)-Andrea- (Woman)': 'es-EC-AndreaNeural',
 'Spanish (Ecuador)-Luis- (Man)': 'es-EC-LuisNeural',
 'Spanish (Spain)-Alvaro- (Man)': 'es-ES-AlvaroNeural',
 'Spanish (Spain)-Elvira- (Woman)': 'es-ES-ElviraNeural',
 'Spanish (Equatorial Guinea)-Teresa- (Woman)': 'es-GQ-TeresaNeural',
 'Spanish (Guatemala)-Andres- (Man)': 'es-GT-AndresNeural',
 'Spanish (Guatemala)-Marta- (Woman)': 'es-GT-MartaNeural',
 'Spanish (Honduras)-Carlos- (Man)': 'es-HN-CarlosNeural',
 'Spanish (Honduras)-Karla- (Woman)': 'es-HN-KarlaNeural',
 'Spanish (Nicaragua)-Federico- (Man)': 'es-NI-FedericoNeural',
 'Spanish (Nicaragua)-Yolanda- (Woman)': 'es-NI-YolandaNeural',
 'Spanish (Panama)-Margarita- (Woman)': 'es-PA-MargaritaNeural',
 'Spanish (Panama)-Roberto- (Man)': 'es-PA-RobertoNeural',
 'Spanish (Peru)-Alex- (Man)': 'es-PE-AlexNeural',
 'Spanish (Peru)-Camila- (Woman)': 'es-PE-CamilaNeural',
 'Spanish (Puerto Rico)-Karina- (Woman)': 'es-PR-KarinaNeural',
 'Spanish (Puerto Rico)-Victor- (Man)': 'es-PR-VictorNeural',
 'Spanish (Paraguay)-Mario- (Man)': 'es-PY-MarioNeural',
 'Spanish (Paraguay)-Tania- (Woman)': 'es-PY-TaniaNeural',
 'Spanish (El Salvador)-Lorena- (Woman)': 'es-SV-LorenaNeural',
 'Spanish (El Salvador)-Rodrigo- (Man)': 'es-SV-RodrigoNeural',
 'Spanish (United States)-Alonso- (Man)': 'es-US-AlonsoNeural',
 'Spanish (United States)-Paloma- (Woman)': 'es-US-PalomaNeural',
 'Spanish (Uruguay)-Mateo- (Man)': 'es-UY-MateoNeural',
 'Spanish (Uruguay)-Valentina- (Woman)': 'es-UY-ValentinaNeural',
 'Spanish (Venezuela)-Paola- (Woman)': 'es-VE-PaolaNeural',
 'Spanish (Venezuela)-Sebastian- (Man)': 'es-VE-SebastianNeural',
'Estonian (Estonia)-Anu- (Woman)': 'et-EE-AnuNeural',
'Estonian (Estonia)-Kert- (Man)': 'et-EE-KertNeural',
'Persian (Iran)-Dilara- (Woman)': 'fa-IR-DilaraNeural',
'Persian (Iran)-Farid- (Man)': 'fa-IR-FaridNeural',
'Finnish (Finland)-Harri- (Man)': 'fi-FI-HarriNeural',
'Finnish (Finland)-Noora- (Woman)': 'fi-FI-NooraNeural',
'French (Belgium)-Charline- (Woman)': 'fr-BE-CharlineNeural',
'French (Belgium)-Gerard- (Man)': 'fr-BE-GerardNeural',
'French (Canada)-Sylvie- (Woman)': 'fr-CA-SylvieNeural',
'French (Canada)-Antoine- (Man)': 'fr-CA-AntoineNeural',
'French (Canada)-Jean- (Man)': 'fr-CA-JeanNeural',
'French (Switzerland)-Ariane- (Woman)': 'fr-CH-ArianeNeural',
'French (Switzerland)-Fabrice- (Man)': 'fr-CH-FabriceNeural',
'Irish (Ireland)-Colm- (Man)': 'ga-IE-ColmNeural',
'Irish (Ireland)-Orla- (Woman)': 'ga-IE-OrlaNeural',
'Galician (Spain)-Roi- (Man)': 'gl-ES-RoiNeural',
'Galician (Spain)-Sabela- (Woman)': 'gl-ES-SabelaNeural',
'Gujarati (India)-Dhwani- (Woman)': 'gu-IN-DhwaniNeural',
'Gujarati (India)-Niranjan- (Man)': 'gu-IN-NiranjanNeural',
'Hindi (India)-Madhur- (Man)': 'hi-IN-MadhurNeural',
'Hindi (India)-Swara- (Woman)': 'hi-IN-SwaraNeural',
'Croatian (Croatia)-Gabrijela- (Woman)': 'hr-HR-GabrijelaNeural',
'Croatian (Croatia)-Srecko- (Man)': 'hr-HR-SreckoNeural',
'Hungarian (Hungary)-Noemi- (Woman)': 'hu-HU-NoemiNeural',
'Hungarian (Hungary)-Tamas- (Man)': 'hu-HU-TamasNeural',
'Icelandic (Iceland)-Gudrun- (Woman)': 'is-IS-GudrunNeural',
'Icelandic (Iceland)-Gunnar- (Man)': 'is-IS-GunnarNeural',
'Javanese (Indonesia)-Dimas- (Man)': 'jv-ID-DimasNeural',
'Javanese (Indonesia)-Siti- (Woman)': 'jv-ID-SitiNeural',
'Georgian (Georgia)-Eka- (Woman)': 'ka-GE-EkaNeural',
'Georgian (Georgia)-Giorgi- (Man)': 'ka-GE-GiorgiNeural',
'Kazakh (Kazakhstan)-Aigul- (Woman)': 'kk-KZ-AigulNeural',
'Kazakh (Kazakhstan)-Daulet- (Man)': 'kk-KZ-DauletNeural',
'Khmer (Cambodia)-Piseth- (Man)': 'km-KH-PisethNeural',
'Khmer (Cambodia)-Sreymom- (Woman)': 'km-KH-SreymomNeural',
'Kannada (India)-Gagan- (Man)': 'kn-IN-GaganNeural',
'Kannada (India)-Sapna- (Woman)': 'kn-IN-SapnaNeural',
'Lao (Laos)-Chanthavong- (Man)': 'lo-LA-ChanthavongNeural',
'Lao (Laos)-Keomany- (Woman)': 'lo-LA-KeomanyNeural',
'Lithuanian (Lithuania)-Leonas- (Man)': 'lt-LT-LeonasNeural',
'Lithuanian (Lithuania)-Ona- (Woman)': 'lt-LT-OnaNeural',
'Latvian (Latvia)-Everita- (Woman)': 'lv-LV-EveritaNeural',
'Latvian (Latvia)-Nils- (Man)': 'lv-LV-NilsNeural',
'Macedonian (North Macedonia)-Aleksandar- (Man)': 'mk-MK-AleksandarNeural',
'Macedonian (North Macedonia)-Marija- (Woman)': 'mk-MK-MarijaNeural',
'Malayalam (India)-Midhun- (Man)': 'ml-IN-MidhunNeural',
'Malayalam (India)-Sobhana- (Woman)': 'ml-IN-SobhanaNeural',
'Mongolian (Mongolia)-Bataa- (Man)': 'mn-MN-BataaNeural',
'Mongolian (Mongolia)-Yesui- (Woman)': 'mn-MN-YesuiNeural',
'Marathi (India)-Aarohi- (Woman)': 'mr-IN-AarohiNeural',
'Marathi (India)-Manohar- (Man)': 'mr-IN-ManoharNeural',
'Maltese (Malta)-Grace- (Woman)': 'mt-MT-GraceNeural',
'Maltese (Malta)-Joseph- (Man)': 'mt-MT-JosephNeural',
'Burmese (Myanmar)-Nilar- (Woman)': 'my-MM-NilarNeural',
'Burmese (Myanmar)-Thiha- (Man)': 'my-MM-ThihaNeural',
'Nepali (Nepal)-Hemkala- (Woman)': 'ne-NP-HemkalaNeural',
'Nepali (Nepal)-Sagar- (Man)': 'ne-NP-SagarNeural',
'Dutch (Belgium)-Arnaud- (Man)': 'nl-BE-ArnaudNeural',
'Dutch (Belgium)-Dena- (Woman)': 'nl-BE-DenaNeural',
'Polish (Poland)-Marek- (Man)': 'pl-PL-MarekNeural',
'Polish (Poland)-Zofia- (Woman)': 'pl-PL-ZofiaNeural',
'Pashto (Afghanistan)-Gul Nawaz- (Man)': 'ps-AF-Gul',}